"""add_patient_info_to_bilan

Revision ID: 5f08c91a2f3b
Revises: 96f5463002a1
Create Date: 2026-02-11 20:46:14.721417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f08c91a2f3b'
down_revision = '96f5463002a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('patient_first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('patient_birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('patient_address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilans', schema=None) as batch_op:
        batch_op.drop_column('patient_address')
        batch_op.drop_column('patient_birth_date')
        batch_op.drop_column('patient_first_name')
        batch_op.drop_column('patient_last_name')

    # ### end Alembic commands ###
