"""add tutor_id to children

Revision ID: 77bbafd3fb56
Revises: 3a7ad1e3a47e
Create Date: 2026-01-10 16:57:34.009646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bbafd3fb56'
down_revision = '3a7ad1e3a47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('model_audio_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_initial_test', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('evaluation_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('course_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('evaluation_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_children_tutor_id_users', 'users', ['tutor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('evaluation_score')
        batch_op.drop_column('course_level')
        batch_op.drop_column('evaluation_level')
        batch_op.drop_column('has_initial_test')
        batch_op.drop_column('tutor_id')

    op.drop_table('training_exercises')
    # ### end Alembic commands ###
