"""add_bilan_table

Revision ID: 96f5463002a1
Revises: 9f74a17ed1ee
Create Date: 2026-02-11 14:28:25.456814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f5463002a1'
down_revision = '9f74a17ed1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bilans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('orthophonist_name', sa.String(length=100), nullable=True),
    sa.Column('deficiency_congenital', sa.Boolean(), nullable=True),
    sa.Column('deficiency_age_appearance', sa.String(length=50), nullable=True),
    sa.Column('age_diagnosis', sa.String(length=50), nullable=True),
    sa.Column('age_first_fitting', sa.String(length=50), nullable=True),
    sa.Column('schooling_type', sa.String(length=50), nullable=True),
    sa.Column('schooling_specialized_detail', sa.String(length=255), nullable=True),
    sa.Column('deafness_degree_od', sa.String(length=20), nullable=True),
    sa.Column('deafness_degree_og', sa.String(length=20), nullable=True),
    sa.Column('deafness_evolutionary', sa.Boolean(), nullable=True),
    sa.Column('equipment_od', sa.Boolean(), nullable=True),
    sa.Column('equipment_og', sa.Boolean(), nullable=True),
    sa.Column('equipment_ci', sa.Boolean(), nullable=True),
    sa.Column('date_equipment_current', sa.Date(), nullable=True),
    sa.Column('date_implantation', sa.Date(), nullable=True),
    sa.Column('communication_modes', sa.JSON(), nullable=True),
    sa.Column('multimodal_detail', sa.String(length=255), nullable=True),
    sa.Column('human_aid_necessity', sa.Boolean(), nullable=True),
    sa.Column('human_aid_detail', sa.String(length=255), nullable=True),
    sa.Column('phone_communication_aided', sa.Boolean(), nullable=False),
    sa.Column('phone_communication_unaided', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bilans')
    # ### end Alembic commands ###
